version: '3.5'

services:
  nextjs:
    image: ld-nextjs
    container_name: ld-nextjs
    restart: 'always'
    logging:
      options:
        max-size: '10m'
    build:
      context: .
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - ./.next/cache/images:/app/.next/cache/images
    env_file:
      - .env